spring:
  datasource:
    url: jdbc:sqlserver://slaticketmanagementsystem.database.windows.net:1433;database=SLATicketManagement
    username: Admin123
    password: Sla123Admin
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver